### PR TITLE
Adds support for batch voting

### LINKED ISSUE #65: support POST /v1/batch/surveyor/voting in the ledger
requires brave-intl/bat-ledger#240 to be merged into master for staging & production; until then, run the https://github.com/brave-intl/bat-ledger/tree/support-batched-votes branch locally

### PR DESCRIPTION
**Pull request by NejcZdovc**
Resolves #65

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@evq @mrose17 currently getting 404 for

[ response for PUT https://ledger-staging.mercury.basicattentiontoken.org/v2/batch/surveyor/voting ]

**Comment by NejcZdovc** [comment]
it's POST and not PUT, thx @evq

**Comment by jasonrsadler** [comment]
@NejcZdovc Can you rebase? My tests merge caused a conflict here.

**Comment by NejcZdovc** [comment]
@mrose17 sure not a problem

**Comment by NejcZdovc** [comment]
@mrose17 tests added for batch preparation

**Pull request merged**
